### ISSUE TITLE
Button is huge with themes.

### ISSUE THREAD

**Issue by coreyg142** [mozilla/pulse#122]
Title says it all really, the issue can be seen here: [imgur](http://i.imgur.com/QUBCaEt.png)

I am using FT DeepDark 14.2.6, I am not sure if it affects other themes or not.

**Comment by chuckharmston** [comment]
Thanks for the report!

This is an odd one, and unfortunately I don't think there's much I can do about it. Firefox sets a height and width that restricts the size of page action icons to ensure that this doesn't happen. For example, on a Mac: https://dxr.mozilla.org/mozilla-central/source/browser/themes/osx/browser.css#1632-1637. I'd guess that the theme strips this rule, but doesn't replace it with anything.

Do you know if the theme's code is open-sourced? I'd be happy to follow up with the author.

**Comment by SoftVision-PaulOiegas** [comment]
It's huge indeed, I'm using the same theme on the Fx release version. 😆 
Here is the developer website http://stefrosselli.com/en/home and email info@stefrosselli.com . It would be nice to have a fix for this, since it's one of the most used complete themes for Firefox.
Let me know if you want me to contact him.

**Comment by chuckharmston** [comment]
I've followed up with an email to Stefano. Fingers crossed!

**Comment by chuckharmston** [comment]
@ThatOneLegion @SoftVision-PaulOiegas Good news! Stefano will be pushing a fix to the theme this evening.
