### ISSUE TITLE
Submit data to Ping Centre

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#17]
After assembling a full data packet, it should be submitted to Ping Centre.

CC @6a68, who is working on the library that should handle this.

**Comment by chuckharmston** [comment]
We now have [metrics documentation](https://github.com/mozilla/pulse/blob/master/docs/metrics.md), and this is unblocked.

@emtwo, I believe you're the gatekeeper on the Ping Centre side. What do I need to do to begin?

**Comment by emtwo** [comment]
hey @chuckharmston! The ping centre client lives here: https://github.com/mozilla/ping-centre. The README describes what you need to know to get started, but most important thing is to make a PR with your schema here: https://github.com/mozilla/ping-centre/tree/master/schemas. Preferably, it should extend the existing common schema so that we can easily auto-generate dashboards for it.

Note that ping-centre client exists on npm here: https://www.npmjs.com/package/ping-centre however it's not the latest version that's published. I plan to also have https://github.com/mozilla/ping-centre/issues/35 fixed soon so that you can easily use it in the browser.

Please also sync up with @tspurway so he can set you up with a topic and tables for storing the data. Let me know if you have any further questions.

**Comment by jaredhirsch** [comment]
@chuckharmston You don't need to do anything in your addon code to send pings to Ping Centre: `testpilot-metrics` sends events to the Test Pilot addon, and I'm working on a PR which has the Test Pilot addon send events to both Telemetry and Ping Centre.

The part where data sent to Ping Centre turns into a dashboard isn't fully hashed out yet, but you can still start sending data. You can watch [this Ping Centre bug](https://github.com/mozilla/ping-centre/issues/34#issuecomment-277291749) to follow the discussion, for now. Once this is hashed out, I'll add some docs to the Test Pilot repo and give a shout in the status mtg.
