### ISSUE TITLE
Ping counts seem incorrect.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/pulse#175]
[This query](https://sql.telemetry.mozilla.org/queries/4209#8377) illustrates that there are more `pulse-prompted` pings than all others combined, which should not happen. Per [metrics documentation](https://github.com/mozilla/pulse/blob/master/docs/metrics.md#lifecycle), a `pulse-prompted` ping should always be followed by one of `pulse-dismissed` or `pulse-loaded` (which should then be followed by `pulse-unloaded` or `pulse-submitted` ping). It's unclear whether this is a code or data problem.

Two asks:

- @harterrt would you mind giving me a confidence level that the data in redash is currently accurate?
- @SoftVision-PaulOiegas could you have your team try to reproduce a situation where the above-linked lifecycle is not respected in the latest release on production? This can be done by watching the browser console, ensuring that pings of each event are correctly logged, then checking about:telemetry to ensure that pings of each event are also submitted. If something is wrong, the `pulse-submitted` one would be my guess as to where the problem is.

Thanks!

**Comment by harterrt** [comment]
Hey Chuck,

That query is stratified by day, which makes it difficult for me to tell how many `pulse-prompted` pings there are. [This query](https://sql.telemetry.mozilla.org/queries/4212/source) shows `pulse-prompted` pings in the middle of the pack. Does that seem reasonable?

**Comment by chuckharmston** [comment]
@harterrt It's stratified by day because we only added that ping last week; a lifecycle (as defined in the doc above) should be encapsulated in ~10 minutes.

**Comment by harterrt** [comment]
Ah, I didn't see the chart associated with that query - there's an explosion of `pulse-prompted` starting in April. I'll take a closer look.

**Comment by Softvision-VladBacia** [comment]
@chuckharmston , I've investigated a bit this issue and found a couple of things that may be related to this:

1. In `about:preferences` set "Show your windows and tabs from last time" when Nightly starts, trigger a `pulse-loaded` ping and then close the browser from "X" button. In this case there won't be a `pulse-unloaded` event.

2. Have a new profile, 1 tab is opened, trigger a `pulse-loaded` ping and then close the browser from "X" button. Also, in this case there won't be a `pulse-unloaded` event.

3. Have a new profile, trigger a `pulse-loaded` ping for a page by clicking on the pulse icon from the URL bar, rate the page, and when the two drop-down menus are overlaid click on the one with the rating,  and then continue with the whole survey process. At the end there won't be a `pulse-submitted` event.
- This issue is frequently happening after scenario [1] or [2], e10s ON or OFF .

![pulse-submitted_missing](https://cloud.githubusercontent.com/assets/9248513/24969371/45e92ba2-1fb9-11e7-9b85-8d6b035cfc93.gif)

**Comment by harterrt** [comment]
The [raw ping data](https://gist.github.com/harterrt/b4f36ac7d4901f8f07b6fdf8552c0123) appear to have the same issue so this is probably not related to the data pipelining/transformation.

**Comment by SoftVision-CarmenFat** [comment]
Hi @chuckharmston, 
I also investigated this issue and I think I might found a scenario that can be used in order to reproduce the ping lifecycle problem.

STR:
1. Using a new profile, open a window with a couple of websites. 
2. Take one of the opened tabs and drag and drop it so that a new Window is created.
3. In the new Window, click on the Pulse URL button to trigger the feedback panel (the “pulse-loaded” ping is displayed in the Browser Console);
4. Complete the survey by rating the website and click the “Submit” button.

**After step 4, there is no “Submitted object” displayed in the Browser console.**

As a side note, I dragged and dropped the same tab back to the previous Window and following the steps to reproduce above, the behaviour was the same, but it only affected the same tab; the other ones had the “Submitted object” shown in the Browser Console).
For more details, please see the following video record: goo.gl/exD6xR

**Comment by chuckharmston** [comment]
I've released [v1.1.2](https://github.com/mozilla/pulse/milestone/5), which should resolve this issue. @SoftVision-PaulOiegas, can your team verify?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @chuckharmston. Yes, we already started looking over this. I have assigned @SoftVision-CarmenFat again to look over it. She will probably update here the results.

**Comment by SoftVision-CarmenFat** [comment]
Hi @chuckharmston,

I've looked again over this issue using Pulse version 1.1.2 and here are my results:

1. On my side, following the steps to reproduce from my previous scenario in comment 7, the "Submitted object" is now displayed in the Browser console. Still, the side note that I mentioned (dragging and dropping the tab back to its previous Window and then submitting the feedback) is still reproducible, this meaning that only that tab is not displaying a "Submitted object" in the Browser console after submitting the feedback. I should also mention that after dragging and dropping the tab back to the previous Window, the Pulse button from the URL bar is not displayed anymore and it appears only after refreshing the website.
For more details, please see the following video: https://goo.gl/YHI4Is

2. As for @Softvision-VladBacia scenarios, I can still reproduce the first two ones ("pulse-unloaded" events are not displayed in the Browser console after clicking the Close button), but the third scenario seems that it was fixed, since the "Submitted object" appears in the console after submitting the survey with the provided steps to reproduce. 
For more details, please see the following video:
![no unloaded](https://cloud.githubusercontent.com/assets/26000308/25137618/ffdf2e84-2460-11e7-900e-814589509b35.gif)

Please let me know if there are any specific scenarios that you would like me to verify.
